### PR TITLE
Feature/components with tailwind

### PR DESCRIPTION
**Pull request by Kischa-hub**
creating Atoms and Melcous 
1- Option Group 
2- Privacy
3- User Info 
4- result Expanded
fixing Image Upload

### CODE REVIEW

**Review by omarawad0 — COMMENTED** [review]
Looks good, especially the toggle button.
but for now i have some comments:
- why the Image Upload doesn't have a cursor of a pointer. this is so important. and it's not exactly vertically aligned, it needs less padding-top.
- you should using h1 and h2 instead of divs on "Image Upload" and "uploading" texts and so on.

**Comment by omarawad0** [comment]
have a look at the option group. the outer SVG besides the input field needs some margin.

**Comment by Kischa-hub** [comment]
> Looks good, especially the toggle button.
> but for now i have some comments:
> 
> * why the Image Upload doesn't have a cursor of a pointer. this is so important. and it's not exactly vertically aligned, it needs less padding-top.
> * you should using h1 and h2 instead of divs on "Image Upload" and "uploading" texts and s

**Comment by Kischa-hub** [comment]
> Looks good, especially the toggle button.
> but for now i have some comments:
> 
> * why the Image Upload doesn't have a cursor of a pointer. this is so important. and it's not exactly vertically aligned, it needs less padding-top.
> * you should using h1 and h2 instead of divs on "Image Upload" and "uploading" texts and so on.

I have did the following Changes but the second point I don't think so

**Pull request closed without merging**
