### PR TITLE
Creating text options

### PR DESCRIPTION
**Pull request by Safei-Ashraf**
Creating poll text options

### CODE REVIEW

**Review by saifaldin — CHANGES_REQUESTED** [review]
One of the options should be marked with a check mark ( ✓ ), which is the one you chose.

**Comment by Safei-Ashraf** [comment]
added check mark

**Review by saifaldin — DISMISSED** [review]
Use the same check mark from the design, with the same spacing.

**Comment by Safei-Ashraf** [comment]
adjusted svg with sizing and spacing

**Review by eslamheshamm — DISMISSED** [review]
LGTM

**Review by amagdy46 — APPROVED** [review]

**Pull request merged**
