### PR TITLE
Add atoms

### PR DESCRIPTION
**Pull request by Sahl-A**
## All atoms and molecules added with snapshot tests along with their stories. 
- Atoms
-- Toggle
-- Slider
-- Radio
-- Divider
-- Input
-- SelectDropDown
- Molecules
-- Tab 

- Add eslintcache to gitignore
- Add 8 icons as components  
-- poll-outlined
-- file-outlined
-- image-outlined
-- stars
-- ThumpsDown-outlined
-- ThumpsDown
-- ThumpsUp-outlined
-- ThumpsUp

### CODE REVIEW

**Review by Safei-Ashraf — CHANGES_REQUESTED** [review]
It's almost 2 AM, am half dead half-blind, but I did enjoy this 🤝 Nice work.


**### Summary:**

- [x] Great Work in general.
- [x] Tests are great and working properly.
- [x] Be nicer to storybook controls.
- [x] minimal style adjustments needed.

### Details:

All tests behave as intended.✔️⚠️
Atoms
-- ⚠️Toggle > toggle was displayed in 4 separate stories, it could be easily adjusted into a single story with 2 controls (size + disabled)  just like you have done with the checkbox story.

-- ⚠️ Radio > it seems like you are using 3 "actual" controls to the story, please remove the extra 2 fields, and if possible consider using options list or radio select over text areas for storybook in general (ik it does not apply on the label field).

-- ⚠️ Divider classeName should not be in story controls, please replace it with a list of options, also the divider works when it is set to horizontal, on vertical it vanishes off the screen, I tried to inspect it classes seem to change but unable to find it tbh.

-- 😮😮 Input THAT'S A PRETTY NICE COMPONENT!, some small issues with styling when adding prefix it overflows behind the borders unlike the design, also please set the bg of the input container, prefix and icon areas so it matches the design in unified bg colour this could be ignored, but it would be helpful if the component is displayed onto a multi-coloured background as in the photo.

Hint: to make it even more AWESOME you might wanna add cursor-pointer to the (x) icon 

image

-- ⚠️ SelectDropDown: seem to be missing the arrow down icon (default behaviour), would recommend styling the HTML element itself instead of using SVG, less effort and a little bit faster,  also the SVG does not seem to be visible to view, but it exists in dom tree.
image
image

Styles does not match design, review fonts settings and colour.

Molecules
-- ⚠️ Tab
Great work with options on comp.
Please consider adjusting the story to limit it to the needed options (removing className and onClick) or replacing them with a list of possible options in form of list or radio.

The white dot in the label is not centred as in design, it took me a while to tell the difference but setting the white point to top:0 and left:0 seems to solve the issue, it 1~2 px diff.
image
image

**Comment by Sahl-A** [comment]
First of all, Very nice (عظمة على عظمة) and elegant review. 
-- Toggle:> Fixed storybook controls
-- Radio:> Fixed storybook controls
-- Divider:> Added a fixed height to show it. However, it wan't showing as I used h-full which should take its container height later.
-- Input:> I attached a snapshot of the input with highlighting it with green background to make a good contrast. I don't see the different background colors
-- I removed the select arrow SVG, used html. 
input background
-- SelectDropDown:> It's a reusable comp, I left the styles for later when using more advanced techniques to adjust the styling
-- Radio:> I attached a snapshot that shows it is centered. I see your point but I don't know how to fix it. I tried to change the pxls as you recommended. However, it didn't work 
Radio centered

**Review by Safei-Ashraf — CHANGES_REQUESTED** [review]
-- Toggle:> working well, now for cleaning up you could rename the story and remove the other 3 cases you have listed.
image
--Radio:> still got the 2  unused controls (no clue what they should do, also it is not nice to use class name into story controls)
image
Also, it shows a primary coloured dot with no white in it at all 
image

--divider: added width and color to it, still unable to view it in the vertical state (with or without it) it shows undefined class in the classist and disappears 🤷‍♀️ but now I still can see it in the dom tree, so that's a plus
image
-- Input:>  you can use the storybook options to change bg dark, light or default to view how your elements would work on different bg's, this is what I meant in the photo below
image
 >> Also adjust border for upload input to be 1px instead of 2, replacing the border-2 class in tw with  just "border" will do that for you.
 >> I understand it is reusable, yet it still should be able to show the test input not overlayed or hidden partially  I typed +20 to match the state of the design and could not see it, typed "+2000" and that's all I could see,  also it does not show the drop down icon "if there should be any"
 
image

if that was all part of the plan then it's all fine, we could re-check styles later 🤝


 
image
Also consider replacing the icon text area to radio options with whatever options you have allowed the comp to accept or "none"
image

**Comment by Sahl-A** [comment]
- The extra stories of the toggle were removed
- The radio unnecessary controls were removed
- The radio appearance were adjusted
- The devider is shown in vertical position as in the snapshot
Divider vertical Add-Atoms PR
- The input bg is fixed and looks good in dark background as below:
input fix Add-Atoms PR
- The styles of the dropdown select is adjusted. However, it is not fully production ready as I will modify it later when working on components re-usability.
- Last point, It was intended to leave it a string as it is written for the sake of demonstration. It will be changed later when working on re-usability. I plan to make it open for all the icons not only couple of options. This will be implemented later.

**Review by Safei-Ashraf — APPROVED** [review]

**Pull request merged**
