### PR TITLE
Add 2 testing libraries & add eslintcache to gitigonre

### PR DESCRIPTION
**Pull request by Sahl-A**
- Added the following packages:
-- @testing-library/jest-dom
-- @testing-library/react
- Created setupTests.js & added import for jest-dom
- Added dummy.test.js to test the configuration works
- Added eslintcache to gitignore

### CODE REVIEW

**Review by Nilegfx — CHANGES_REQUESTED** [review]
too much changes. doesn't match the description

**Comment by Sahl-A** [comment]
@Nilegfx 
- Removed the unnecessary tests.
- Removed the unnecessary installed packages.
- Add a dummy test file to check the configuration.

**Review by Safei-Ashraf — APPROVED** [review]
LGTM

**Review by Nilegfx — APPROVED** [review]
LGTM

**Pull request merged**
