### PR TITLE
added test buttons section

### PR DESCRIPTION
**Pull request by Ali-Khamis**
##description
-added variants of buttons with tailwind classes WITHOUT any customs css style

### CODE REVIEW

**Review by eslamheshamm — CHANGES_REQUESTED** [review]
Good Work, Ali,
But consider
1- the border shows only when the user clicks on the button(focus state)
2-The Icon in the disabled (Secondary + Right Icon)  button, not the same color as the text
Keep going dude

**Comment by omarawad0** [comment]
All sounds good.
but I was wondering why you didn't use the default primary color for buttons. you're using the shades as the default.

**Comment by Ali-Khamis** [comment]
because I needed a darker color for the borders and the hover

**Review by omarawad0 — APPROVED** [review]
LGTM

**Review by eslamheshamm — APPROVED** [review]
LGTM

**Pull request merged**
